language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sunilkumar9/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sunilkumar9/docker-react npm run test