language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sunilkumar9/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sunilkumar9/docker-react npm run test  -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-038358149844"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
